# Generated by Django 4.0.1 on 2022-01-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designer', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=300)),
                ('color', models.CharField(max_length=20)),
                ('price', models.PositiveIntegerField()),
                ('buy_now', models.CharField(max_length=300)),
                ('category', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
    ]
