# Generated by Django 4.0.1 on 2022-02-11 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designer', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=300)),
                ('color', models.CharField(choices=[('Black', 'Black'), ('Blue', 'Blue'), ('Brown', 'Brown'), ('Camel', 'Camel'), ('Cream', 'Cream'), ('Green', 'Green'), ('Grey', 'Grey'), ('Lilac', 'Lilac'), ('Mixed', 'Mixed'), ('Natural', 'Natural'), ('Olive', 'Olive'), ('Peach', 'Peach'), ('Pink', 'Pink'), ('Purple', 'Purple'), ('Red', 'Red'), ('Sand', 'Sand'), ('White', 'White'), ('Yellow', 'Yellow'), ('N/A', 'N/A')], max_length=20)),
                ('price', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('Accessories', 'Accessories'), ('Clothing', 'Clothing'), ('Shoes', 'Shoes'), ('Beauty + Lifestyle', 'Beauty + Lifestyle')], max_length=50)),
                ('type', models.CharField(choices=[('Accessories', (('Bags', 'Bags'), ('Gloves', 'Gloves'), ('Hair', 'Hair'), ('Hats', 'Hats'), ('Jewellery', 'Jewellery'), ('Socks', 'Socks'), ('Sunglasses', 'Sunglasses'), ('Tights', 'Tights'))), ('Clothing', (('Coats + Jackets', 'Coats + Jackets'), ('Dresses', 'Dresses'), ('Jeans', 'Jeans'), ('Knitwear', 'Knitwear'), ('Shorts', 'Shorts'), ('Skirts', 'Skirts'), ('Sweatshirt', 'Sweatshirt'), ('T-shirts', 'T-shirts'), ('Trackpants', 'Trackpants'), ('Trousers', 'Trousers'))), ('Shoes', (('Boots', 'Boots'), ('Flats', 'Flats'), ('Heels', 'Heels'), ('Trainers', 'Trainers'))), ('Beauty + Lifestyle', (('Skincare', 'Skincare'), ('Makeup', 'Makeup'), ('Home', 'Home')))], max_length=50)),
                ('featured_product', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_products', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Wardrobe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_in_wardrobe', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_wardrobe_of', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingBag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_in_shopping_bag', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_shopping_bag_of', to='products.product')),
            ],
        ),
    ]
