# Generated by Django 4.0.1 on 2022-01-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Clothing', 'Clothing'), ('Accessories', 'Accessories'), ('Bags', 'Bags'), ('Shoes', 'Shoes')], max_length=50),
        ),
    ]
