# Generated by Django 4.0.1 on 2022-01-23 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_wishlist_owner_shoppingbag'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('One Size', 'One Size'), ('Skincare', 'Skincare')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Accessories', (('Bags', 'Bags'), ('Gloves', 'Gloves'), ('Hair', 'Hair'), ('Hats', 'Hats'), ('Jewellery', 'Jewellery'), ('Socks', 'Socks'), ('Sunglasses', 'Sunglasses'), ('Tights', 'Tights'))), ('Clothing', (('Coats + Jackets', 'Coats + Jackets'), ('Dresses', 'Dresses'), ('Jeans', 'Jeans'), ('Knitwear', 'Knitwear'), ('Shorts', 'Shorts'), ('Skirts', 'Skirts'), ('Sweatshirt', 'Sweatshirt'), ('T-shirts', 'T-shirts'), ('Trousers', 'Trousers'), ('Underwear', 'Underwear'))), ('Shoes', (('Boots', 'Boots'), ('Flats', 'Flats'), ('Heels', 'Heels'), ('Trainers', 'Trainers'))), ('Skincare', (('Cleansers', 'Cleansers'), ('Eyes + Lips', 'Eyes + Lips'), ('Moisturisers', 'Moisturisers'), ('Serums', 'Serums'), ('Suncream', 'Suncream'), ('Tools', 'Tools')))], max_length=50),
        ),
    ]
