# Generated by Django 4.0.1 on 2022-01-23 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_size_alter_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
