# Generated by Django 4.0.1 on 2022-01-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('Black', 'Black'), ('Blue', 'Blue'), ('Grey', 'Grey'), ('Lilac', 'Lilac'), ('Mixed', 'Mixed'), ('Pink', 'Pink'), ('White', 'White')], max_length=20),
        ),
    ]
