# Generated by Django 4.0.1 on 2022-01-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('Black', 'Black'), ('Blue', 'Blue'), ('Brown', 'Brown'), ('Green', 'Green'), ('Grey', 'Grey'), ('Lilac', 'Lilac'), ('Mixed', 'Mixed'), ('Pink', 'Pink'), ('Purple', 'Purple'), ('Red', 'Red'), ('Sand', 'Sand'), ('White', 'White')], max_length=20),
        ),
    ]
