# Generated by Django 4.0.1 on 2022-01-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_product_category_alter_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('Black', 'Black'), ('Blue', 'Blue'), ('Brown', 'Brown'), ('Camel', 'Camel'), ('Cream', 'Cream'), ('Green', 'Green'), ('Grey', 'Grey'), ('Lilac', 'Lilac'), ('Mixed', 'Mixed'), ('Natural', 'Natural'), ('Olive', 'Olive'), ('Peach', 'Peach'), ('Pink', 'Pink'), ('Purple', 'Purple'), ('Red', 'Red'), ('Sand', 'Sand'), ('White', 'White'), ('Yellow', 'Yellow'), ('N/A', 'N/A')], max_length=20),
        ),
    ]
