# Generated by Django 4.0.1 on 2022-01-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featuredProduct',
            field=models.BooleanField(default=False),
        ),
    ]
