# Generated by Django 4.0.1 on 2022-01-26 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_product_featuredproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='featuredProduct',
            new_name='featured_product',
        ),
    ]
